version: "3.8"

services:
  blockscout:
    image: us-central1-docker.pkg.dev/${PROJECT_ID:-minikube}/nameless/blockscout:${DOCKER_TAG:-5.2.2-stealthtest0.1.0}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "true"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.2.2
